export const FETCH_CLASS_NAMES = "FETCH_CLASS_NAMES";
export const FETCH_SUBJECT_NAMES = "FETCH_SUBJECT_NAMES";
export const UPLOAD_HOME_WORK = "UPLOAD_HOME_WORK";
export const RESET_UPLOADER = "RESET_UPLOADER";
export const GET_ALL_HOME_WORK = "GET_ALL_HOME_WORK";
export const FETCH_LASTEST_NEWS = "FETCH_LASTEST_NEWS";
